os: linux
dist: xenial
language: python
addons:
  apt:
    packages:
      - python3-pip
before_install:
  - python -m pip install --upgrade pip
script: 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests;fi'
branches:
  only:
    - main
install:
  - pip install -r requirements.txt
  - pip3 install --upgrade pip
script:
 - python -m unittest tests.test_dice

jobs:
  fast_finish: true 
  include:
    - stage: unit tests
      script: python -m unittest tests.test_dice
    - stage: deploy to staging
      script: skip
      deploy: &heroku
        provider: heroku
        app: pacific-lake-63914 
        api_key: $HEROKU_AUTH_TOKEN
    - stage: test staging
      script: 'curl https://pacific-lake-63914.herokuapp.com/'
    - stage: deploy to production
      script: skip
      deploy:
        <<: *heroku
        app: peaceful-brushlands-68941
    - stage: test production
      script: 'curl https://peaceful-brushlands-68941.herokuapp.com'

  
    

