os: linux
dist: xenial
language: python
addons:
  apt:
    packages:
      - python3-pip

before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt
  - pip3 install --upgrade pip

  script:
 - python -m unittest tests.test_dice


