os: linux
dist: xenial
language: python
addons:
  apt:
    packages:
      - python3-pip
before_install:
  - python -m pip install --upgrade pip
script: 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests;fi'
branches:
  only:
    - main
install:
  - pip install -r requirements.txt
  - pip3 install --upgrade pip
script:
 - python -m unittest tests.test_dice


  
    

